version: 2

project_name: hacs-agent

builds:
  - id: agent
    main: ./agent/main.go
    binary: hacs-agent
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: ["-trimpath"]
    ldflags:
      - -s -w

archives:
  - id: default
    builds: [agent]
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  replace_existing_draft: true
  mode: replace

changelog:
  use: github
