version: '3.8'

services:
  core:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./core:/app
    command: bash -lc "pip install -r requirements.txt && python app.py"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  pair-server:
    build: ./pair-server
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WS_URL=wss://ws.hacs.world/agent
      - PAIR_SECRET=${PAIR_SECRET}
    ports:
      - "8001:8000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
