name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ai-core image
        run: docker build -t hacs-core:ci ./core
      - name: Python checks
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r core/requirements.txt
      - run: python -c "import sentence_transformers; print('embedder ok')" 
