name: build-and-smoke

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (core)
        run: docker build -t hacs-core:test ./core

      - name: Run container
        run: |
          docker run -d --rm --name hacs-ci \
            -e API_KEY="testkey" \
            -e APP_MODULE="core.app:app" \
            -e PORT=8000 \
            -p 8000:8000 \
            hacs-core:test

      - name: Smoke (sanity light)
        run: |
          bash ./scripts/sanity.sh

      - name: Show logs on failure
        if: failure()
        run: docker logs hacs-ci || true

      - name: Stop container
        if: always()
        run: docker stop hacs-ci || true
