name: build-and-smoke
on: [push]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps for smoke
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build image (core)
        run: docker build -t hacs-core:test ./core

      - name: Prepare CI .env (no secrets)
        run: |
          cat > core/.env <<'EOF'
          API_KEY=changeme
          ALLOWLIST=wikipedia.org,docs.python.org,ffmpeg.org,arxiv.org,github.com,x.ai
          USE_GENERATION=none
          AUTOSAVE_SEC=10
          MEMORY_PATH=./state/memory.json
          HUMOR_MODE=friendly
          REGION=ru-RU
          HUMOR_USER_NAME=бро
          EOF

      - name: Run container
        run: |
          docker run -d --rm --name hacs-ci \
            -p 8000:8000 \
            -v ${{ github.workspace }}/core/state:/app/state \
            -v ${{ github.workspace }}/core/outputs:/app/outputs \
            --env-file core/.env \
            hacs-core:test
          # небольшой wait на старт uvicorn
          for i in {1..30}; do
            if curl -fsS -H "X-API-Key: changeme" http://127.0.0.1:8000/health >/dev/null; then
              echo "app is up"; break
            fi
            sleep 1
          done

      - name: Smoke (sanity light)
        env:
          API: http://127.0.0.1:8000
          API_KEY: changeme
        run: bash scripts/sanity.sh

      - name: Stop container
        if: always()
        run: docker stop hacs-ci
