name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/hacs-core
  CI_API_KEY: ci-test-key                 # ключ для /health и sanity
  HOST_PORT: "18000"                      # внешний порт раннера (внутри контейнера слушаем 8000)

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps for smoke (curl+jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl jq

      - name: Build image (core)
        run: |
          docker build -t hacs-core:test ./core

      - name: Prepare CI .env (no secrets)
        run: |
          mkdir -p core
          cat > core/.env.ci <<'EOF'
          API_KEY=${{ env.CI_API_KEY }}
          ALLOWLIST=wikipedia.org,docs.python.org,ffmpeg.org,arxiv.org,github.com,x.ai
          USE_GENERATION=none
          GROK_API_KEY=
          GROK_MODEL=grok-4-fast
          OLLAMA_MODEL=llama3.1:8b
          AUTOSAVE_SEC=10
          MEMORY_PATH=./state/memory.json
          HUMOR_MODE=friendly
          REGION=ru-RU
          HUMOR_USER_NAME=бро
          EOF

      - name: Run container
        run: |
          mkdir -p data/state data/outputs data/vault
          docker run -d --name hacs-ci \
            --env-file core/.env.ci \
            -p $HOST_PORT:8000 \
            -v $PWD/data/state:/app/state \
            -v $PWD/data/outputs:/app/outputs \
            -v $PWD/data/vault:/app/vault:ro \
            hacs-core:test

          echo "→ wait for /health on http://127.0.0.1:${HOST_PORT}"
          for i in {1..90}; do
            if curl -fsS -H "X-API-Key: $CI_API_KEY" http://127.0.0.1:${HOST_PORT}/health >/dev/null; then
              echo "service is up"; exit 0
            fi
            sleep 1
          done
          echo "Service did not become ready in time"
          docker logs hacs-ci || true
          exit 1

      - name: Smoke (sanity light)
        env:
          API: http://127.0.0.1:${{ env.HOST_PORT }}
          API_KEY: ${{ env.CI_API_KEY }}
        run: |
          bash scripts/sanity.sh

      - name: Show logs on failure
        if: failure()
        run: |
          docker ps -a
          echo "---- container logs ----"
          docker logs --tail=200 hacs-ci || true

      - name: Stop container
        if: always()
        run: |
          docker rm -f hacs-ci || true

  push-image:
    needs: build-and-smoke
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./core
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
