name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (core)
        run: docker build -t hacs-core:test .

      - name: Prepare CI .env (no secrets)
        run: |
          cat > .env.ci <<EOF
          API_KEY=changeme
          ALLOWLIST=wikipedia.org,docs.python.org,ffmpeg.org,arxiv.org,github.com,x.ai
          USE_GENERATION=none
          AUTOSAVE_SEC=30
          MEMORY_PATH=./state/memory.json
          HUMOR_MODE=off
          REGION=ru-RU
          HUMOR_USER_NAME=ci
          EOF

      - name: Run container
        run: |
          docker run -d --rm \
            --name hacs-ci \
            --env-file .env.ci \
            -p 8000:8000 \
            hacs-core:test

      - name: Smoke (sanity light)
        env:
          API: http://127.0.0.1:8000
          API_KEY: changeme
          BOOT_WAIT: "5"
        run: bash ../scripts/sanity.sh

      - name: Show logs on failure
        if: failure()
        run: |
          docker ps -a
          echo "---- container logs ----"
          docker logs hacs-ci || true

      - name: Stop container
        if: always()
        run: docker stop hacs-ci || true

  push-image:
    if: github.ref == 'refs/heads/main' && success()
    needs: build-and-smoke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        working-directory: core
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/hacs-core:${{ github.sha }}
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
