name: CI

on:
  push:
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (core)
        run: |
          docker build -t hacs-core:test ./core

      - name: Run container
        env:
          API_KEY: changeme
        run: |
          docker run -d --rm --name hacs-ci \
            -e API_KEY="${API_KEY}" \
            -p 8000:8000 \
            hacs-core:test
          # показать логи старта фоном (если упадёт — увидим почему)
          (sleep 1; docker logs -f hacs-ci &) >/dev/null 2>&1 || true

      - name: Smoke (sanity light)
        env:
          API: http://127.0.0.1:8000
          API_KEY: changeme
        run: |
          chmod +x scripts/sanity.sh
          ./scripts/sanity.sh

      - name: Stop container
        if: always()
        run: docker ps -q --filter "name=hacs-ci" | xargs -r docker stop

      - name: Show logs on failure
        if: failure()
        run: docker logs hacs-ci || true

  push-image:
    needs: build-and-smoke
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.GHCR_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build & Push
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/hacs-core:${{ github.sha }}
          docker build -t "$IMAGE" ./core
          docker push "$IMAGE"
