name: build-and-smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (core)
        run: |
          docker build -t hacs-core:test ./core

      - name: Prepare CI .env (no secrets)
        run: |
          cat > core/.env << 'EOF'
          API_KEY=ci-key
          ALLOWLIST=wikipedia.org,docs.python.org,ffmpeg.org,arxiv.org,github.com,x.ai
          USE_GENERATION=none
          GROK_API_KEY=
          GROK_MODEL=grok-4-fast
          OLLAMA_MODEL=llama3.1:8b
          AUTOSAVE_SEC=5
          MEMORY_PATH=./state/memory.json
          HUMOR_MODE=friendly
          REGION=ru-RU
          HUMOR_USER_NAME=ci
          EOF

      - name: Run container
        run: |
          # порт наружу CI-вм не нужен, тестируем изнутри раннера
          docker run -d --rm \
            --name hacs-ci \
            -p 127.0.0.1:8000:8000 \
            --env-file core/.env \
            hacs-core:test

      - name: Smoke (sanity light)
        env:
          API: http://127.0.0.1:8000
          API_KEY: ci-key
        run: |
          bash ./scripts/sanity_ci.sh

      - name: Show logs on failure
        if: failure()
        run: |
          docker ps -a
          echo "---- container logs ----"
          docker logs hacs-ci || true

      - name: Stop container
        if: always()
        run: docker stop hacs-ci || true
